<?php
namespace frontend\widgets\nav;

use Yii;
use yii\base\Widget;
use yii\base\InvalidConfigException;
use yii\helpers\ArrayHelper;

class Footer extends Widget
{
    public $link;
    public $linksTop;
    public $linksHeader;
    public $breadcrumbs;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (empty($this->link)) {
            throw new InvalidConfigException("The 'link' property has not been set.");
        }

        if (empty($this->linksTop)) {
            throw new InvalidConfigException("The 'linksTop' property has not been set.");
        }

        if (empty($this->linksHeader)) {
            throw new InvalidConfigException("The 'linksHeader' property has not been set.");
        }
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $asset = NavAsset::register($this->view);
        $breadcrumbsId = ArrayHelper::index($this->breadcrumbs, 'id');

        echo $this->render('footerNav', ['linksTop' => $this->linksTop, 'linksHeader' => $this->linksHeader, 'breadcrumbsId' => $breadcrumbsId]);
    }
}