<?php

namespace common\models\shop;

use common\models\helpers\Translit;
use Yii;
use common\models\main\Contents;
use common\models\gallery\GalleryImages;

/**
 * This is the model class for table "shop_property_values".
 *
 * @property integer $id
 * @property integer $shop_properties_id
 * @property string $name
 * @property string $anchor
 * @property string $url
 * @property integer $contents_id
 * @property integer $gallery_images_id
 *
 * @property GalleryImages $galleryImage
 * @property ShopPropertyValues $shopProperty
 */
class ShopPropertyValues extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'shop_property_values';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shop_properties_id', 'contents_id', 'gallery_images_id'], 'integer'],
            [['name', 'anchor', 'url'], 'string', 'max' => 255],
            [['shop_properties_id'], 'exist', 'skipOnError' => true, 'targetClass' => ShopProperties::className(), 'targetAttribute' => ['shop_properties_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'shop_properties_id' => 'Shop Properties ID',
            'name' => 'Name',
            'anchor' => 'Anchor',
            'url' => 'Url',
            'contents_id' => 'Contents ID',
            'gallery_images_id' => 'Gallery Images ID'
        ];
    }

    public function getShopProperty()
    {
        return $this->hasOne(ShopProperties::className(), ['id' => 'shop_properties_id']);
    }

    public function getContent()
    {
        return $this->hasOne(Contents::className(), ['id' => 'contents_id']);
    }

    public function getGalleryImage()
    {
        return $this->hasOne(GalleryImages::className(), ['id' => 'gallery_images_id']);
    }

    public function beforeSave($insert)
    {
        if (!$this->url) {
            $translit = new Translit();
            $this->url = $insert ? $translit->slugify($this->anchor, $this->tableName(), 'anchor', '_', $this->id, 'shop_properties_id', $this->shop_properties_id) : $translit->slugify($this->anchor, $this->tableName(), 'anchor', '_', null, 'shop_properties_id', $this->shop_properties_id);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
