<?php

namespace common\models\sms;

use Yii;

/**
 * This is the model class for table "sms_contacts".
 *
 * @property integer $id
 * @property string $phone
 * @property string $name
 * @property string $surname
 * @property string $patronymic
 * @property string $dob
 * @property integer $female
 * @property string $male
 * @property string $email
 * @property string $card_number
 * @property string $delivery_address
 * @property string $date_registration
 * @property integer $control
 * @property integer $state
 * @property integer $created_at
 *
 * @property SmsSendContacts[] $smsSendContacts
 */
class SmsContacts extends \yii\db\ActiveRecord
{
    public $gender = 0;
    public $genders = ['Не указано', 'Мужской', 'Женский'];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sms_contacts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['dob', 'date_registration'], 'safe'],
            [['female', 'control', 'state', 'created_at', 'gender'], 'integer'],
            [['phone', 'name', 'surname', 'patronymic', 'male', 'email', 'card_number'], 'string', 'max' => 255],
            [['email'], 'email'],
            [['delivery_address'], 'string', 'max' => 512],
            [['phone'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'phone' => 'Мобильный телефон',
            'name' => 'Имя',
            'surname' => 'Фамилия',
            'patronymic' => 'Отчество',
            'dob' => 'Дата рождения',
            'female' => 'Female',
            'male' => 'Male',
            'email' => 'Адрес электронной почты',
            'card_number' => 'Card Number',
            'delivery_address' => 'Delivery Address',
            'date_registration' => 'Date Registration',
            'control' => 'Control',
            'gender' => 'Пол',
            'state' => 'Желание получать оповещения',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSmsSendContacts()
    {
        return $this->hasMany(SmsSendContacts::className(), ['sms_contacts_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created_at = time();
        }

        $this->phone = preg_replace('/[^0-9]/', '', $this->phone);
        if (strlen($this->phone) == 11 && substr($this->phone, 0, 1) == 8) {
            $this->phone = '7'.substr($this->phone, 1);
        }

        switch ($this->gender) {
            case 0: $this->female = 0; $this->male = 0; break;
            case 1: $this->female = 0; $this->male = 1; break;
            case 2: $this->female = 1; $this->male = 0; break;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
