<?php
namespace backend\modules\shop\models;

use Yii;
use common\models\shop\ShopGoodProperties;

class GoodPropertiesForm extends ShopGoodProperties
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}