<?php
namespace backend\modules\shop\models;

use common\models\shop\ShopGoodProperties;
use common\models\shop\ShopPropertyValues;
use Yii;
use yii\helpers\ArrayHelper;
use common\models\shop\ShopGoods;
use common\models\shop\ShopGroupProperties;
use common\models\shop\ShopUnits;

class GoodForm extends ShopGoods
{
    public $propertyValues;
    public $units;

    public function rules()
    {
        return array_merge(parent::rules(), [
            ['propertyValues', 'each', 'rule' => ['string']],
        ]);
    }

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
            'shop_units_id' => 'Еденица измерения',
            'code' => 'Код товара',
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->units = ArrayHelper::map(ShopUnits::find()->all(), 'id', 'name');
        $this->units[] = 'Не указано';
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        ShopGoodProperties::deleteAll(['shop_goods_id' => $this->id]);

        foreach ($this->propertyValues as $shop_properties_id => $anchor) {
            $shopPropertyValue = ShopPropertyValues::find()
                ->where(['shop_properties_id' => $shop_properties_id])
                ->andWhere(['anchor' => $anchor])
                ->one();
            if (!$shopPropertyValue) {
                $shopPropertyValue = new ShopPropertyValues();
                $shopPropertyValue->shop_properties_id = $shop_properties_id;
                $shopPropertyValue->name = $anchor;
                $shopPropertyValue->anchor = $anchor;
                $shopPropertyValue->save();
            }

            $shopGoodProperty = new ShopGoodProperties();
            $shopGoodProperty->shop_goods_id = $this->id;
            $shopGoodProperty->shop_properties_id = $shop_properties_id;
            $shopGoodProperty->shop_property_values_id = $shopPropertyValue->id;
            $shopGoodProperty->state = true;
            $shopGoodProperty->save();
        }
    }
}