<?php
namespace backend\modules\shop\models;

use Yii;
use yii\helpers\ArrayHelper;
use common\models\shop\ShopGroups;
use common\models\shop\ShopGroupProperties;

class GroupForm extends ShopGroups
{
    public function rules()
    {
        return array_merge(parent::rules(), []);
    }

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), []);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        $oldGroupProperties = ShopGroupProperties::find()->where(['shop_groups_id' => $this->id])->all();
        if ($oldGroupProperties) {
            $existProperties = array();

            /**
             * @var integer $i
             * @var ShopGroupProperties $oldGroupProperty
             */
            foreach ($oldGroupProperties as $i => $oldGroupProperty) {
                if (array_search($oldGroupProperty->shop_properties_id, $this->groupProperties) !== false) $existProperties[] = $oldGroupProperty->shop_properties_id;
            }

            foreach ($oldGroupProperties as $oldGroupProperty) {
                if (array_search($oldGroupProperty->shop_properties_id, $existProperties))
                if (empty($oldGroupProperty['exist'])) {
                    ShopGroupProperties::deleteAll(['shop_groups_id' => $oldGroupProperty->shop_groups_id, 'shop_properties_id' => $oldGroupProperty->shop_properties_id]);
                }
            }
        }

        if ($this->groupProperties) {
            for ($i=0; $i < count($this->groupProperties); $i++) {
                if (!$oldGroupProperties or array_search($this->groupProperties[$i], ArrayHelper::getColumn($oldGroupProperties, 'shop_properties_id')) === false) {
                    $shopGroupProperty = new ShopGroupProperties();
                    $shopGroupProperty->shop_groups_id = $this->id;
                    $shopGroupProperty->shop_properties_id = $this->groupProperties[$i];
                    $shopGroupProperty->save();
                }
            }
        }
    }
}