<?php
namespace backend\modules\shop\models;

use common\models\helpers\Translit;
use common\models\main\Contents;
use Yii;
use common\models\main\Links;

class LinkGoodForm extends Links
{
    public $state = true;
    public $text;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->parent = Yii::$app->request->get('parent');
        $this->categories_id = Yii::$app->params['shop']['categoriesId'];
        $this->views_id = Yii::$app->params['shop']['good_views_id'];
    }

    public function rules()
    {
        return array_merge(parent::rules(),[
            [['text'], 'string'],
        ]);
    }

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
            'state' => 'Активная (опубликованная) группа',
            'anchor' => 'Наименование',
        ]);
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

        if ($this->id) {
            $this->text = Contents::findOne(['links_id' => $this->id, 'seq' => 1])->text;
        } else {
            $this->text = '';
        }
    }

    public function beforeSave($insert)
    {
        $translit = new Translit();
        if (!$this->name) $this->name = isset($this->id) ? $translit->slugify($this->anchor, $this->tableName(), 'name', '-', $this->id) : $translit->slugify($this->anchor, $this->tableName(), 'name', '-', null);
        if (!$this->title) $this->title = $this->anchor;
        if (!$this->seq) $this->seq = isset($this->id) ? $this->seq : Links::findLastSequence(Yii::$app->params['shop']['categoriesId'], $this->parent) + 1;
        $this->created_at = isset($this->id) ? $this->created_at : time();
        $this->updated_at = time();

        $content = Contents::findOne(['links_id' => $this->id, 'seq' => 1]);
        if (!$content) {
            $content = new Contents();
        }
        $content->links_id = $this->id;
        $content->seq = 1;
        $content->text = $this->text;
        $content->save();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}