<?php
namespace backend\modules\shop\models;

use common\models\main\Links;
use yii\helpers\ArrayHelper;

class ProductFormForm extends Links
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }
}