<?php
namespace app\modules\items\models;

use Yii;
use common\models\main\Contents;
use common\models\items\Items;

class ItemForm extends Items
{
    public $text;

    public function rules()
    {
        return array_merge(parent::rules(),[
            [['text'], 'string'],
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->state = $this->state ?: true;
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub

        $this->text = $this->contents_id ? Contents::findOne($this->contents_id)->text : '';
    }

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
            'text' => 'Контент',
        ]);
    }
}