<?php
namespace backend\widgets\map;

use common\models\main\Links;
use Yii;
use common\models\main\Categories;
use kartik\base\InputWidget;
use kartik\helpers\Html;
use yii\bootstrap\Dropdown;
use yii\helpers\Json;
use yii\bootstrap\Modal;
use yii\helpers\ArrayHelper;

class SelectLink extends InputWidget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $asset = SelectLinkAsset::register($this->view);

        echo $form = Html::tag('div', Html::activeHiddenInput($this->model, $this->attribute, $this->options), ['id' => 'input-'.$this->getId()]);

        $opts = Json::encode([
            'url' => $asset->baseUrl,
            'inputId' => $this->options['id'],
            'modelName' => $this->attribute,
            'modelValue' => $this->model[$this->attribute],
        ]);
        $this->view->registerJs("$('#content-{$this->id}').selectLink({$opts});");

        $categories = Categories::find()->orderBy(['seq' => SORT_ASC])->all();
        $categoriesId = $categories[0]->id;
        $parent = null;

        if (!$this->model[$this->attribute]) {
            $modalUrl = 'Ссылка не выбрана';
            $modalTargetUrl = 'Выбрать';
            $modalValue = null;
        } else {
            $modalUrl = $this->getUrl($this->model[$this->attribute]);
            $modalTargetUrl = $modalUrl;
            $modalValue = $this->model[$this->attribute];
        }

        echo Html::tag('div', '', ['id' => 'content-'.$this->id]);
        Modal::begin([
            'header' => 'Выбор ссылки',
            'footer' => Html::a('Отмена', '#', ['data-dismiss' => 'modal', 'class' => 'btn btn-default btn-flat btn-sm']) .
                        Html::a('Выбрать', '#', ['class' => 'btn btn-primary btn-flat btn-sm', 'onclick' => 'selectLink.confirmChoose()']) .
                        Html::a('Удалить', '#', ['class' => 'btn btn-danger btn-flat btn-sm hide', 'onclick' => 'selectLink.delete()']),
            'toggleButton' => [
                'tag' => 'a',
                'label' => $modalTargetUrl,
                'id' => 'modal-show-'.$this->options['id'],
                'onClick' => 'selectLink.getLinks("'.$categoriesId.'", "'.$parent.'")',
            ],
            'options' => [
                'id' => 'modal-'.$this->options['id'],
            ],
        ]);

        echo Html::beginTag('div', ['class' => 'form-group']);
        echo Html::label('Категория');
        echo Html::dropDownList(null, null, ArrayHelper::map($categories, 'id', 'comment'), [
            'class' => 'form-control',
            'onChange' => 'selectLink.getLinks($(this).val(), null)',
        ]);
        echo Html::endTag('div');

        echo Html::beginTag('div', ['class' => 'form-group']);
        echo Html::label('Выберете ссылку');
        echo Html::tag('div', '', ['id' => 'map-'.$this->attribute]);
        echo Html::endTag('div');

        echo Html::tag('div', '<div id="'.$this->options['id'].'-choose-url">'.$modalUrl.'</div>', ['class' => 'form-group']);
        echo Html::tag('div', '<div id="'.$this->options['id'].'-choose-links_id" class="hide">'.$modalValue.'</div>', ['class' => 'form-group']);

        Modal::end();
    }

    private function getUrl($linksId)
    {
        $link = Links::findOne($linksId);
        $url = '/'.$link->anchor;
        if ($link->parent !== null) {
            $parent = $link->parent;

            do {
                $link = Links::findOne($parent);
                $parent = $link->parent;
                $url = '/'.$link->anchor.$url;
            } while($parent !== null);
        }

        return $url;
    }
}