<?php

namespace app\modules\sms\models;

use Yii;
use yii\base\Model;
use common\models\sms\SmsSendContacts;

class RenderSendForm extends Model
{
    public $contact_ids;
    public $sms_send_id;

    public function rules()
    {
        return [
            [['contact_ids'], 'required'],
            [['sms_send_id'], 'integer'],
//            [['contact_ids'], 'each', ['rule' => 'integer']]
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function load($data, $formName = null)
    {
        parent::load($data, $formName); // TODO: Change the autogenerated stub

        $sendContacts = SmsSendContacts::find()->where(['sms_send_id' => $this->sms_send_id])->all();
        if ($sendContacts) {
            /** @var SmsSendContacts $sendContact */
            foreach ($sendContacts as $sendContact) {
                if (array_search($sendContact->id, $this->contact_ids) === false) {
                    SmsSendContacts::deleteAll(['id' => $sendContact->id]);
                }
            }
        }

        return true;
    }
}